apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - srh.yaml
  - backend.yaml
  - web.yaml
  - hpa-backend.yaml
  - hpa-web.yaml
