apiVersion: apps/v1
kind: Deployment
metadata:
  name: srh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srh
  template:
    metadata:
      labels:
        app: srh
    spec:
      containers:
        - name: srh
          image: hiett/serverless-redis-http:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PORT
              value: "80"
          volumeMounts:
            - name: srh-config
              mountPath: /app/srh-config
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
      volumes:
        - name: srh-config
          configMap:
            name: srh-config
---
apiVersion: v1
kind: Service
metadata:
  name: srh
spec:
  selector:
    app: srh
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: srh-config
data:
  tokens.json: |
    {
      "local_dev_token": "redis://redis:6379"
    }
